### ISSUE TITLE
add github actions for building the extension image 

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/yarahunter-docker-extension#1]
Add github actions yml to build the image on every PR/commit

**Comment by GJS2162** [comment]
@ibreakthecloud I want to work on this ,could you assign this to me?

**Comment by ibreakthecloud** [comment]
sure @GJS2162 .
While you are at it, https://github.com/deepfence/secretscanner-docker-extension/issues/1 this is the similar issue and efforts would be same. Let me know if you would like it assigned too.
