### ISSUE TITLE
update README with development steps

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/yarahunter-docker-extension#2]
Add local development section in README with steps:

- to enable Chrome dev tool: console logs, network, source, etc.
- enable hot reloading: to use local ui code without rebuilding
ref: https://www.docker.com/blog/build-your-first-docker-extension/

**Comment by Such6** [comment]
Can you assign me this issue

**Comment by ibreakthecloud** [comment]
Done! @Such6

**Comment by Such6** [comment]
Can you review it

**Comment by Such6** [comment]
Can you review the changes

**Comment by ibreakthecloud** [comment]
> Can you review the changes

Please check PR :)

**Comment by Such6** [comment]
I have updated as per your instructions. So you want the images to be there or should I remove them.

**Comment by ibreakthecloud** [comment]
> I have updated as per your instructions. So you want the images to be there or should I remove them.

I have given some suggestions, we need to remove the images

**Comment by Such6** [comment]
@ibreakthecloud done

**Comment by ibreakthecloud** [comment]
> @ibreakthecloud done

merged thanks! @Such6
