### ISSUE TITLE
external repo link target should be default browser

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/yarahunter-docker-extension#3]
The problem
clicking on deepfence github buttons, renders github inside the docker desktop.

Expectation
Upon clicking any of the two buttons, open the GitHub url in the default browser.

<img width="933" alt="image" src="https://user-images.githubusercontent.com/18168330/194998810-0487ceca-8884-44c6-beb7-975ae2a25748.png">

**Comment by akashyadav24** [comment]
Hi can you assign it to me

**Comment by ibreakthecloud** [comment]
sure @akashyadav24
