### ISSUE TITLE
Add blank slate and loading animation

### ISSUE THREAD

**Issue by ibreakthecloud** [deepfence/yarahunter-docker-extension#4]
Add blank slate for the following conditions
- Initially when nothing is scanned
- When there is no result in the scan

Also, add animation in empty table view when scan is in progress

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/18168330/195047390-2f6b713b-428c-4f12-b4ea-d299bcc4b483.png">

**Comment by yogesh-9999** [comment]
Hey @ibreakthecloud  assign this to me

**Comment by ibreakthecloud** [comment]
> Hey @ibreakthecloud  assign this to me

Done.

**Comment by ibreakthecloud** [comment]
@yogesh-9999 pls. refer to this: https://github.com/deepfence/secretscanner-docker-extension/pull/7
